# Generated by Django 3.1.1 on 2020-09-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_urls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='active_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
